font:
  size: 16.0
  normal:
    family: SpaceMono Nerd Font 

live_config_reload: true
cursor:
  style: Block
  unfocused_hollow: true


mouse:
  hints:
    lancher:
      program: open
    modifiers: Command

# Define
schemes:
  chalk: &chalk
    colors:
      bright:
        black: '#888888'
        blue: '#4196ff'
        cyan: '#53cdbd'
        green: '#80c470'
        magenta: '#fc5275'
        red: '#f24840'
        white: '#d2d8d9'
        yellow: '#ffeb62'
      cursor:
        cursor: '#708284'
        text: '#002831'
      normal:
        black: '#7d8b8f'
        blue: '#2a7fac'
        cyan: '#44a799'
        green: '#789b6a'
        magenta: '#bd4f5a'
        red: '#b23a52'
        white: '#d2d8d9'
        yellow: '#b9ac4a'
      primary:
        background: '#2b2d2e'
        foreground: '#d2d8d9'
      selection:
        background: '#e4e8ed'
        text: '#3f4041'
  gruvbox_material_hard_dark: &gruvbox_material_hard_dark
    primary:
      background: '0x1d2021'
      foreground: '0xd4be98'
    normal:
      black:   '0x32302f'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xd8a657'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      cyan:    '0x89b482'
      white:   '0xd4be98'
    bright:
      black:   '0x32302f'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xd8a657'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      cyan:    '0x89b482'
      white:   '0xd4be98'
  gruvbox_material_medium_dark: &gruvbox_material_medium_dark
    primary:
      background: '0x282828'
      foreground: '0xd4be98'
    normal:
      black:   '0x3c3836'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xd8a657'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      cyan:    '0x89b482'
      white:   '0xd4be98'
    bright:
      black:   '0x3c3836'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xd8a657'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      cyan:    '0x89b482'
      white:   '0xd4be98'
  gruvbox_material_soft_dark: &gruvbox_material_soft_dark
    primary:
      background: '0x32302f'
      foreground: '0xd4be98'
    normal:
      black:   '0x45403d'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xd8a657'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      cyan:    '0x89b482'
      white:   '0xd4be98'
    bright:
      black:   '0x45403d'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xd8a657'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      cyan:    '0x89b482'
      white:   '0xd4be98'
  gruvbox_material_hard_light: &gruvbox_material_hard_light
    primary:
      background: '0xf9f5d7'
      foreground: '0x654735'
    normal:
      black:   '0x654735'
      red:     '0xc14a4a'
      green:   '0x6c782e'
      yellow:  '0xb47109'
      blue:    '0x45707a'
      magenta: '0x945e80'
      cyan:    '0x4c7a5d'
      white:   '0xf2e5bc'
    bright:
      black:   '0x654735'
      red:     '0xc14a4a'
      green:   '0x6c782e'
      yellow:  '0xb47109'
      blue:    '0x45707a'
      magenta: '0x945e80'
      cyan:    '0x4c7a5d'
      white:   '0xf2e5bc'
  gruvbox_material_medium_light: &gruvbox_material_medium_light
    primary:
      background: '0xfbf1c7'
      foreground: '0x654735'
    normal:
      black:   '0x654735'
      red:     '0xc14a4a'
      green:   '0x6c782e'
      yellow:  '0xb47109'
      blue:    '0x45707a'
      magenta: '0x945e80'
      cyan:    '0x4c7a5d'
      white:   '0xeee0b7'
    bright:
      black:   '0x654735'
      red:     '0xc14a4a'
      green:   '0x6c782e'
      yellow:  '0xb47109'
      blue:    '0x45707a'
      magenta: '0x945e80'
      cyan:    '0x4c7a5d'
      white:   '0xeee0b7'
  gruvbox_material_soft_light: &gruvbox_material_soft_light
    primary:
      background: '0xf2e5bc'
      foreground: '0x654735'
    normal:
      black:   '0x654735'
      red:     '0xc14a4a'
      green:   '0x6c782e'
      yellow:  '0xb47109'
      blue:    '0x45707a'
      magenta: '0x945e80'
      cyan:    '0x4c7a5d'
      white:   '0xe6d5ae'
    bright:
      black:   '0x654735'
      red:     '0xc14a4a'
      green:   '0x6c782e'
      yellow:  '0xb47109'
      blue:    '0x45707a'
      magenta: '0x945e80'
      cyan:    '0x4c7a5d'
      white:   '0xe6d5ae'

  kangawa: &kangawa
    primary:
      background: '0x1f1f28'
      foreground: '0xdcd7ba'

    normal:
      black:   '0x090618'
      red:     '0xc34043'
      green:   '0x76946a'
      yellow:  '0xc0a36e'
      blue:    '0x7e9cd8'
      magenta: '0x957fb8'
      cyan:    '0x6a9589'
      white:   '0xc8c093'

    bright:
      black:   '0x727169'
      red:     '0xe82424'
      green:   '0x98bb6c'
      yellow:  '0xe6c384'
      blue:    '0x7fb4ca'
      magenta: '0x938aa9'
      cyan:    '0x7aa89f'
      white:   '0xdcd7ba'

    selection:
      background: '0x2d4f67'
      foreground: '0xc8c093'

    indexed_colors:
      - { index: 16, color: '0xffa066' }
      - { index: 17, color: '0xff5d62' }

  everforest_dark_hard: &everforest_dark_hard
    primary:
      background: '#2b3339'
      foreground: '#d3c6aa'
    normal:
      black:   '#4b565c'
      red:     '#e67e80'
      green:   '#a7c080'
      yellow:  '#dbbc7f'
      blue:    '#7fbbb3'
      magenta: '#d699b6'
      cyan:    '#83c092'
      white:   '#d3c6aa'
    bright:
      black:   '#4b565c'
      red:     '#e67e80'
      green:   '#a7c080'
      yellow:  '#dbbc7f'
      blue:    '#7fbbb3'
      magenta: '#d699b6'
      cyan:    '#83c092'
      white:   '#d3c6aa'
  everforest_dark_medium: &everforest_dark_medium
    primary:
      background: '#2f383e'
      foreground: '#d3c6aa'
    normal:
      black:   '#4b565c'
      red:     '#e67e80'
      green:   '#a7c080'
      yellow:  '#dbbc7f'
      blue:    '#7fbbb3'
      magenta: '#d699b6'
      cyan:    '#83c092'
      white:   '#d3c6aa'
    bright:
      black:   '#4b565c'
      red:     '#e67e80'
      green:   '#a7c080'
      yellow:  '#dbbc7f'
      blue:    '#7fbbb3'
      magenta: '#d699b6'
      cyan:    '#83c092'
      white:   '#d3c6aa'
  everforest_dark_soft: &everforest_dark_soft
    primary:
      background: '#323d43'
      foreground: '#d3c6aa'
    normal:
      black:   '#4b565c'
      red:     '#e67e80'
      green:   '#a7c080'
      yellow:  '#dbbc7f'
      blue:    '#7fbbb3'
      magenta: '#d699b6'
      cyan:    '#83c092'
      white:   '#d3c6aa'
    bright:
      black:   '#4b565c'
      red:     '#e67e80'
      green:   '#a7c080'
      yellow:  '#dbbc7f'
      blue:    '#7fbbb3'
      magenta: '#d699b6'
      cyan:    '#83c092'
      white:   '#d3c6aa'
  everforest_light_hard: &everforest_light_hard
    primary:
      background: '#fff9e8'
      foreground: '#5c6a72'
    normal:
      black:   '#5c6a72'
      red:     '#f85552'
      green:   '#8da101'
      yellow:  '#dfa000'
      blue:    '#3a94c5'
      magenta: '#df69ba'
      cyan:    '#35a77c'
      white:   '#dfddc8'
    bright:
      black:   '#5c6a72'
      red:     '#f85552'
      green:   '#8da101'
      yellow:  '#dfa000'
      blue:    '#3a94c5'
      magenta: '#df69ba'
      cyan:    '#35a77c'
      white:   '#dfddc8'
  everforest_light_medium: &everforest_light_medium
    primary:
      background: '#fdf6e3'
      foreground: '#5c6a72'
    normal:
      black:   '#5c6a72'
      red:     '#f85552'
      green:   '#8da101'
      yellow:  '#dfa000'
      blue:    '#3a94c5'
      magenta: '#df69ba'
      cyan:    '#35a77c'
      white:   '#dfddc8'
    bright:
      black:   '#5c6a72'
      red:     '#f85552'
      green:   '#8da101'
      yellow:  '#dfa000'
      blue:    '#3a94c5'
      magenta: '#df69ba'
      cyan:    '#35a77c'
      white:   '#dfddc8'
  everforest_light_soft: &everforest_light_soft
    primary:
      background: '#f8f0dc'
      foreground: '#5c6a72'
    normal:
      black:   '#5c6a72'
      red:     '#f85552'
      green:   '#8da101'
      yellow:  '#dfa000'
      blue:    '#3a94c5'
      magenta: '#df69ba'
      cyan:    '#35a77c'
      white:   '#dfddc8'
    bright:
      black:   '#5c6a72'
      red:     '#f85552'
      green:   '#8da101'
      yellow:  '#dfa000'
      blue:    '#3a94c5'
      magenta: '#df69ba'
      cyan:    '#35a77c'
      white:   '#dfddc8'

# Apply
colors: *everforest_dark_soft

key_bindings:
  - { key: V,        mods: Command,       action: Paste                        }
  - { key: C,        mods: Command,       action: Copy                         }
  - { key: Q,        mods: Command,       action: Quit                         }
  - { key: N,        mods: Command,       action: SpawnNewInstance             }
  - { key: Return,   mods: Command,       action: ToggleFullscreen             }

  - { key: J,        mods: Alt,     chars: "\x1bj"                       }
  - { key: K,        mods: Alt,     chars: "\x1bk"                       }
  - { key: H,        mods: Alt,     chars: "\x1bh"                       }
  - { key: L,        mods: Alt,     chars: "\x1bl"                       }

  - { key: Home,                          chars: "\x1bOH",   mode: AppCursor   }
  - { key: Home,                          chars: "\x1b[H",   mode: ~AppCursor  }
  - { key: End,                           chars: "\x1bOF",   mode: AppCursor   }
  - { key: End,                           chars: "\x1b[F",   mode: ~AppCursor  }
  - { key: Equals,   mods: Command,       action: IncreaseFontSize             }
  - { key: Minus,    mods: Command,       action: DecreaseFontSize             }
  - { key: Minus,    mods: Command|Shift, action: ResetFontSize                }
  - { key: PageUp,   mods: Shift,         chars: "\x1b[5;2~"                   }
  - { key: PageUp,   mods: Control,       chars: "\x1b[5;5~"                   }
  - { key: PageUp,                        chars: "\x1b[5~"                     }
  - { key: PageDown, mods: Shift,         chars: "\x1b[6;2~"                   }
  - { key: PageDown, mods: Control,       chars: "\x1b[6;5~"                   }
  - { key: PageDown,                      chars: "\x1b[6~"                     }
  - { key: Left,     mods: Shift,         chars: "\x1b[1;2D"                   }
  - { key: Left,     mods: Control,       chars: "\x1b[1;5D"                   }
  - { key: Left,                          chars: "\x1b[D",   mode: ~AppCursor  }
  - { key: Left,                          chars: "\x1bOD",   mode: AppCursor   }
  - { key: Right,    mods: Shift,         chars: "\x1b[1;2C"                   }
  - { key: Right,    mods: Control,       chars: "\x1b[1;5C"                   }
  - { key: Right,                         chars: "\x1b[C",   mode: ~AppCursor  }
  - { key: Right,                         chars: "\x1bOC",   mode: AppCursor   }
  - { key: Up,       mods: Shift,         chars: "\x1b[1;2A"                   }
  - { key: Up,       mods: Control,       chars: "\x1b[1;5A"                   }
  - { key: Up,       mods: Alt,           chars: "\x1b[1;3A"                   }
  - { key: Up,                            chars: "\x1b[A",   mode: ~AppCursor  }
  - { key: Up,                            chars: "\x1bOA",   mode: AppCursor   }
  - { key: Down,     mods: Shift,         chars: "\x1b[1;2B"                   }
  - { key: Down,     mods: Control,       chars: "\x1b[1;5B"                   }
  - { key: Down,     mods: Alt,           chars: "\x1b[1;3B"                   }
  - { key: Down,                          chars: "\x1b[B",   mode: ~AppCursor  }
  - { key: Down,                          chars: "\x1bOB",   mode: AppCursor   }
  - { key: Tab,      mods: Shift,         chars: "\x1b[Z"                      }
  - { key: F1,                            chars: "\x1bOP"                      }
  - { key: F2,                            chars: "\x1bOQ"                      }
  - { key: F3,                            chars: "\x1bOR"                      }
  - { key: F4,                            chars: "\x1bOS"                      }
  - { key: F5,                            chars: "\x1b[15~"                    }
  - { key: F6,                            chars: "\x1b[17~"                    }
  - { key: F7,                            chars: "\x1b[18~"                    }
  - { key: F8,                            chars: "\x1b[19~"                    }
  - { key: F9,                            chars: "\x1b[20~"                    }
  - { key: F10,                           chars: "\x1b[21~"                    }
  - { key: F11,                           chars: "\x1b[23~"                    }
  - { key: F12,                           chars: "\x1b[24~"                    }
  - { key: Back,                          chars: "\x7f"                        }
  - { key: Back,     mods: Alt,           chars: "\x1b\x7f"                    }
  - { key: Insert,                        chars: "\x1b[2~"                     }
  - { key: Delete,                        chars: "\x1b[3~"                     }

# Skip words
  - { key: Left,     mods: Alt,     chars: "\x1bb"                       } # Skip word left
  - { key: Right,    mods: Alt,     chars: "\x1bf"                       } # Skip word right
  - { key: Left,     mods: Command, chars: "\x1bOH",   mode: AppCursor   } # Home
  - { key: Right,    mods: Command, chars: "\x1bOF",   mode: AppCursor   } # End
  - { key: Back,     mods: Command, chars: "\x15"                        } # Delete line
  - { key: Back,     mods: Alt,     chars: "\x1b\x7f"                    } # Delete word


    # shortcuts for tmux. the leader key is control-b (0x02)
  - { key: W,        mods: Command,       chars: "\x02&"                       }  # close tab (kill)
  - { key: T,        mods: Command,       chars: "\x02c"                       }  # new tab
  - { key: RBracket, mods: Command|Shift, chars: "\x02n"                       }  # select next tab
  - { key: LBracket, mods: Command|Shift, chars: "\x02p"                       }  # select previous tab
  - { key: RBracket, mods: Command,       chars: "\x02o"                       }  # select next pane
  - { key: LBracket, mods: Command,       chars: "\x02;"                       }  # select last (previously used) pane
  - { key: F,        mods: Command,       chars: "\x02/"                       }  # search (upwards) (see tmux.conf)
