[General]
#################### General ####################

ScreenWidth="3840"
ScreenHeight="2160"
ScreenPadding="0"

Font="JetBrainsMono Nerd Font"
FontSize="12"

KeyboardSize="0.4"
RoundCorners="6"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd d"

HeaderText=""

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/mono-black.png"
BackgroundSpeed=""
PauseBackground=""
DimBackground="0.0"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

HeaderTextColor="#ffffff"
DateTextColor="#888888"
TimeTextColor="#ffffff"

FormBackgroundColor="#0a0a0a"
BackgroundColor="#000000"
DimBackgroundColor="#000000"

LoginFieldBackgroundColor="#1a1a1a"
PasswordFieldBackgroundColor="#1a1a1a"
LoginFieldTextColor="#ffffff"
PasswordFieldTextColor="#ffffff"
UserIconColor="#ffffff"
PasswordIconColor="#ffffff"

PlaceholderTextColor="#666666"
WarningColor="#ffffff"

LoginButtonTextColor="#000000"
LoginButtonBackgroundColor="#ffffff"
SystemButtonsIconsColor="#ffffff"
SessionButtonTextColor="#ffffff"
VirtualKeyboardButtonTextColor="#ffffff"

DropdownTextColor="#ffffff"
DropdownSelectedBackgroundColor="#1a1a1a"
DropdownBackgroundColor="#0a0a0a"

HighlightTextColor="#000000"
HighlightBackgroundColor="#ffffff"
HighlightBorderColor="#ffffff"

HoverUserIconColor="#888888"
HoverPasswordIconColor="#888888"
HoverSystemButtonsIconsColor="#888888"
HoverSessionButtonTextColor="#888888"
HoverVirtualKeyboardButtonTextColor="#888888"

#################### Form ####################

PartialBlur="false"
FullBlur="false"
BlurMax="32"
Blur="1.0"

HaveFormBackground="false"
FormPosition="center"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="true"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

#################### Translation ####################

TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateSessionSelection=""
TranslateVirtualKeyboardButtonOn=""
TranslateVirtualKeyboardButtonOff=""
