git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}" --syntax-theme "ansi"
os:
  editPreset: "nvim-remote"
  # edit: "nvim --server $NVIM --remote-send '<C-\\><C-n>:close | edit {{filename}}<CR>'"
  # editAtLine: "nvim --server $NVIM --remote-send '<C-\\><C-n>:close | edit {{filename}}<CR>:{{line}}<CR>'"
