;;; ghostel-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ghostel.el

(autoload 'ghostel "ghostel" "\
Start a new Ghostel terminal.  If the buffer already exists, switch to it.
With a non-numeric prefix arg, create a new buffer.
With a numeric prefix ARG, switch to the buffer with that number or
create it if it doesn't exist yet.
The name of the buffer is determined by the value of `ghostel-buffer-name'.
Returns the buffer.

(fn &optional ARG)" t)
(autoload 'ghostel-project "ghostel" "\
Start a new Ghostel terminal in the current project's root.
The buffer name is prefixed with the project name.
If a buffer already exists for this project, switch to it.
Otherwise create a new Ghostel buffer.  ARG is passed through to
`ghostel' and accepts the same universal argument conventions.
To add this to `project-switch-commands':
  (add-to-list \\='project-switch-commands \\='(ghostel-project \"Ghostel\") t)
Returns the buffer.

(fn &optional ARG)" t)
(register-definition-prefixes "ghostel" '("ghostel-"))


;;; Generated autoloads from ghostel-compile.el

(autoload 'ghostel-compile "ghostel-compile" "\
Run COMMAND in a ghostel terminal with compilation integration.

Like \\[compile], but uses a ghostel buffer so programs that require
a real TTY work correctly.  The buffer gets a compilation-mode-like
header and footer, and when the command finishes the major mode is
switched to `ghostel-compile-finished-major-mode' (by default
`ghostel-compile-view-mode', derived from `compilation-mode').
Error locations become available through `next-error'.

COMMAND is passed verbatim to `shell-file-name -c', so multi-line
scripts work exactly as in \\[shell-command].  No shell-integration
setup is required — the process sentinel reports the real exit
status.

If optional second arg INTERACTIVE is non-nil the buffer is a
writable ghostel terminal during the run.
Otherwise (the default) the buffer is read-only and behaves like a
`compilation-mode' buffer with `g' reruns, `n'/`p' walk errors, etc.

Interactively, prompts for the command if option
`compilation-read-command' is non-nil, otherwise uses
`compile-command'.  With prefix arg, always prompts.

Output always scrolls as it arrives (equivalent to
`compilation-scroll-output' being non-nil).  `compilation-ask-about-save'
and `compilation-auto-jump-to-first-error' are honoured.  The command
default and history are shared with \\[compile] via `compile-command'
and `compile-history'.

(fn COMMAND &optional INTERACTIVE)" t)
(defvar ghostel-compile-global-mode nil "\
Non-nil if Ghostel-Compile-Global mode is enabled.
See the `ghostel-compile-global-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `ghostel-compile-global-mode'.")
(custom-autoload 'ghostel-compile-global-mode "ghostel-compile" nil)
(autoload 'ghostel-compile-global-mode "ghostel-compile" "\
Global minor mode: route all `compile'-style calls through ghostel.

When enabled, advises `compilation-start' so that \\[compile],
\\[recompile], \\[project-compile], and every other caller that
goes through `compilation-start' runs in a ghostel terminal —
giving you a real TTY for progress bars, colours, and curses tools
without having to switch commands.

The default routing is read-only: a plain \\[compile] (or any caller
passing `MODE=nil' / `MODE=compilation-mode') yields a read-only buffer
that behaves like a `compilation-mode' buffer.  Callers asking for the
comint variant (\\[universal-argument] \\[compile], i.e. `MODE=t') are
routed to a writable ghostel terminal - interactive throughout the run,
so programs like `htop' or test prompts work - instead of falling
through to `comint-mode'.  Note: this means `compilation-shell-minor-mode'
is *not* enabled in the interactive variant - its keymap would shadow
`ghostel-mode's input handlers and break key forwarding to the PTY.
Custom `compilation-mode' subclasses yield a read-only buffer that
finalizes into the subclass.

Modes in `ghostel-compile-global-mode-excluded-modes' (by default,
`grep-mode') still use the stock implementation, since their output
parsers and window-management conventions don't fit a live TTY.

This is a global minor mode.  If called interactively, toggle the
`Ghostel-Compile-Global mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='ghostel-compile-global-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "ghostel-compile" '("ghostel-"))


;;; Generated autoloads from ghostel-debug.el

(autoload 'ghostel-debug-password-events-show "ghostel-debug" "\
Display recent password-prompt rising edges.
Shows every fire of `ghostel--detect-password-prompt' along with the
arm that triggered it (libghostty heuristic / regex on remote / regex
on unobservable tty), the cursor row text at the moment, and the
buffer's remote-shell state.  Use this to diagnose spurious
`read-passwd' prompts: the entry that opened the unwanted minibuffer
will identify which detection arm misfired." t)
(autoload 'ghostel-debug-start "ghostel-debug" "\
Start logging ghostel events to *ghostel-debug* buffer.
Logs filter calls, key sends, resize events, redraw decisions
(including DEC 2026 skip/force), and `window-start' anchoring." t)
(autoload 'ghostel-debug-info "ghostel-debug" "\
Display diagnostic info about the ghostel environment.
Collects Emacs version, system info, native module state, frame and
window geometry, terminal state, process info, and any non-default
ghostel settings into *ghostel-debug* for pasting into bug reports.

In a ghostel buffer with a TRAMP `default-directory', also prints a
TRAMP section (version, `tramp-terminal-type', direct-async path,
local-vs-toplevel TERM stripping diagnostics).

When the buffer was started via \\[ghostel-debug-ghostel], also prints
the spawn capture (wrapper script, `process-environment' as sent,
first PTY output bytes, first keystrokes).

With prefix arg WITH-REMOTE-PROBES, runs live probes against the
remote (`infocmp', terminfo path checks, `/bin/sh' identity, login
shell) — adds latency and requires a healthy TRAMP connection, so
omit it when the connection itself is the suspected fault.

(fn &optional WITH-REMOTE-PROBES)" t)
(autoload 'ghostel-debug-ghostel "ghostel-debug" "\
Like `ghostel', but capture spawn diagnostics into the new buffer.

The new buffer carries a snapshot of:
- the wrapper script as sent to `make-process' (with the on-remote
  TERM preamble for TRAMP spawns — the smoking gun for #224-class
  bugs)
- the `process-environment' that ghostel was about to push
- phase timestamps: `ghostel--start-process' entry, `ghostel--spawn-pty'
  entry, first PTY byte received.  The deltas isolate where time goes
  per spawn (elisp prep / TRAMP+ssh / remote shell startup) — useful
  for diagnosing remote-spawn slowness.
- the first ~16 KB of PTY output (did the shell start?  Send a
  prompt?  Garbage?)
- the first ~64 keystrokes you typed

ARG is forwarded to `ghostel' (same prefix-argument conventions).
View the capture with \\[ghostel-debug-info].

(fn &optional ARG)" t)
(autoload 'ghostel-debug-keypress "ghostel-debug" "\
Capture diagnostics for the next keystroke in this ghostel buffer.
After you press one key, a report appears in *ghostel-debug-keypress*
suitable for pasting into a GitHub issue.

Captures the raw event, the resolved keymap binding, every byte that
flowed through `ghostel--send-string' or `ghostel--flush-output' during
the command, terminal mode flags (DECCKM, DECKPAM, bracketed paste,
mouse modes, alt screen, sync output), coalesce-buffer state, and
process state." t)
(register-definition-prefixes "ghostel-debug" '("ghostel-"))


;;; Generated autoloads from ghostel-eshell.el

(autoload 'eshell/ghostel "ghostel-eshell" "\
Run ARGS as a visual command in a dedicated ghostel buffer.
This is an eshell built-in; type `ghostel PROGRAM ...' at the
eshell prompt to launch any program in a ghostel terminal buffer
without adding it to `eshell-visual-commands'.  Dispatches through
`eshell-exec-visual', so when `ghostel-eshell-visual-command-mode'
is enabled the program runs under ghostel; otherwise it falls
back to eshell's default `term-mode' visual handling.

(fn &rest ARGS)")
(defvar ghostel-eshell-visual-command-mode nil "\
Non-nil if Ghostel-Eshell-Visual-Command mode is enabled.
See the `ghostel-eshell-visual-command-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `ghostel-eshell-visual-command-mode'.")
(custom-autoload 'ghostel-eshell-visual-command-mode "ghostel-eshell" nil)
(autoload 'ghostel-eshell-visual-command-mode "ghostel-eshell" "\
Run Eshell visual commands (vim, htop, less, ...) in ghostel buffers.

When enabled, `eshell-exec-visual' is overridden to launch the
program in a dedicated ghostel terminal buffer.  When the program
exits, the buffer stays on `[Process exited]' so any remaining
output is visible; press `q' to dismiss it.  Set
`eshell-destroy-buffer-when-process-dies' to non-nil to kill the
buffer automatically on exit instead.

This is a global minor mode.  If called interactively, toggle the
`Ghostel-Eshell-Visual-Command mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable the
mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='ghostel-eshell-visual-command-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "ghostel-eshell" '("ghostel-eshell-"))

;;; End of scraped data

(provide 'ghostel-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ghostel-autoloads.el ends here
